%YAML:1.0

#--------------------------------------------------------------------------------------------
# viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.render: 1
Viewer.logTiming: 1
Viewer.width: 1024
Viewer.height: 768
Viewer.scaleFactor: 1
Viewer.cameraFollow: 1
Viewer.followDistance: 8

Viewer.currentKeyFrameColor: [0.0,1.0,0.0]
Viewer.allKeyFrameColor: [ 0.0,0.0,1.0]
Viewer.tweenFrameDirectColor: [1.0,0.0,1.0]
Viewer.tweenFrameColor: [0.0,1.0,1.0]
Viewer.mapPointsColor: [0.0,0.0,0.0]
Viewer.mapPointsRefColor: [1.0,0.0,0.0]
Viewer.featureLinesColor: [0.0,1.0,0.0]

Viewer.windowFramesTitle: GLidE-SLAM Frames 2D
Viewer.windowMapTitle: GLidE-SLAM 3D Map
Viewer.mouseMoveFactor: 1
Viewer.fov: 90
Viewer.far: 1000
Viewer.near: 1
Viewer.featuresMaxDepth: 100
#--------------------------------------------------------------------------------------------
# Direct Tracking Parameters
#--------------------------------------------------------------------------------------------
DirTrackParams.runDirectTracking: 0
DirTrackParams.nLevels:           6
DirTrackParams.patchSize:         7
DirTrackParams.scaleFactor:     1.2

DirTrackParams.fx: 535.4
DirTrackParams.fy: 539.2
DirTrackParams.cx: 320.1
DirTrackParams.cy: 247.6

DirTrackParams.maxRecoveryFrames: 1
DirTrackParams.maxFramesDirect: 5
DirTrackParams.maxPoints: 1024
DirTrackParams.enableAlign: 1
DirTrackParams.searchRadius: 5
DirTrackParams.huberK: 0.08
DirTrackParams.epsNorm: 0.0001
DirTrackParams.minPoints: 20
DirTrackParams.maxIterations: 10

DirTrackParams.searchThreshold: [0.012,0.018,0.025,0.035]
DirTrackParams.rejectThreshold: [0.025,0.035,0.050,0.070]
DirTrackParams.maxShift: [3.0,4.0,5.0,6.0]