#version 310 es
precision highp float;

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) uniform highp sampler2D inputTexture;
layout(binding = 1, r32f) writeonly uniform highp image2D outputImage;

uniform ivec2 uDir; // (0,1) or (1,0)

// sigma=1.0, radius=2  => Approximate kernel of 5 weights: [0.0544887, 0.244201, 0.40262, 0.244201, 0.0544887]
const float w0 = 0.4026199469;
const float w1 = 0.2442013420;
const float w2 = 0.0544886850;

float loadClamped(ivec2 p)
{
    ivec2 imageBounds = textureSize(inputTexture, 0);
    p = clamp(p, ivec2(0), imageBounds - ivec2(1));
    return texelFetch(inputTexture, p, 0).r;
}

void main()
{
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imageBounds = textureSize(inputTexture, 0);
    if (pix.x >= imageBounds.x || pix.y >= imageBounds.y) return;

    float sum = loadClamped(pix) * w0;
    sum += loadClamped(pix + uDir * 1) * w1;
    sum += loadClamped(pix - uDir * 1) * w1;
    sum += loadClamped(pix + uDir * 2) * w2;
    sum += loadClamped(pix - uDir * 2) * w2;

    imageStore(outputImage, pix, vec4(sum, 0.0, 0.0, 1.0));
}
