#version 310 es

//need high precision for projection, gradients, jacobian/hessian computations (stability/quantization etc.)
precision highp float;
precision highp int;
precision highp sampler2D;

// Each invocation = one thread = one main() call (here: one map point).
// Total invocations launched = numWorkGroupsX * local_size_x.
// How many run truly in parallel depends on the GPU scheduler / hardware (occupancy).
layout(local_size_x = 64,local_size_y = 1,local_size_z = 1) in;


//Uniforms (read-only constant for all invocations)
uniform mat4  uPose;             //camera pose
uniform vec4  uK;                //intrinsics (pre-scaled for each level)
uniform int   uPatchSize;        //size of patch
uniform int   uLevel;            //current level being processed
uniform sampler2D uRefTexture;  //current level image pyramid

//SSBO bindings (std430 -> standard for SSBOs for alignment of types:
//vec4 16 bytes, uint 4 bytes, float 4 bytes...
//Declare SSBO at slot 1,2,3... contains array ot type vec4/uint/float... buffer handle name
//access by bufferName.member[i]. ->PointsBuffer.pos[i];
layout(std430, binding = 0) readonly  buffer PointsBuffer       {vec4 pos[];   } inMapPoints;
layout(std430, binding = 1) writeonly buffer ValidBuffer        {uint Valid[];} outValid;
layout(std430, binding = 2) writeonly buffer IBuffer            {float IRef[];} outI;
layout(std430, binding = 3) writeonly buffer JBuffer            {float J[];   } outJ;
layout(std430, binding = 4) writeonly buffer HBuffer            {float H[];   } outH;


//helper functions
//return bilinear interpolation (used for projection etc.)
float bilinearSample(float u, float v)
{
    ivec2 size = textureSize(uRefTexture,0); //sample texture at mip level 0
    //normalized coords. (divide by size), sample from pixel center therefore add 0.5 from corner
    vec2 uv = (vec2(u + 0.5, v + 0.5) / vec2(size));
    return texture (uRefTexture,uv).r; //does filtered sampling, texture has only red channel 32 bit float
}

//Hessian per point is 6 x 6 matrix, symmetric
//index starts at 0, a is row, b is offset
int matrixTriangleIndex(int a, int b)
{
    int base = (a * 6) - ((a * (a - 1)) / 2);
    return base + (b - a);
}


void main()
{

    uint ptIndex = gl_GlobalInvocationID.x;

    //check invocation overflow
    if(ptIndex >= uint(PointsBuffer.pos.length()))
        return;


    vec4 ptPos = PointsBuffer.pos[ptIndex];   //world pos
    vec4 ptPosCam = ptPos * uPose;          //wrt to camera
    float X = ptPosCam.x;
    float Y = ptPosCam.y;
    float Z = ptPosCam.z;

    //check point behind camera
    if(Z <= 0.0)
    {
        outValid[ptIndex] = 0u;
        return;
    }

    float fx = uK.x;
    float fy = uK.y;
    float cx = uK.z;
    float cy = uK.w;

    float u = fx * (X / Z) + cx;
    float v = fy * (Y / Z) + cy;

    ivec2 size = textureSize(uRefTexture,0);
    float width  = float(size.x);
    float height = float(size.y);


    //check if out-of-bounds
    float patchCenter = float(uPatchSize - 1) * 0.5;
    float border      = patchCenter + 2.0;
    if((u < border) || ( v < border) || (u >= (width - border)) || (v >= (height - boder)))
    {
        outValid[ptIndex] = 0u;
        return;
    }

    outValid[ptIndex] = 1u;

    int patchArea = uPatchSize * uPatchSize;

    //set starting index (1D arrays)
    uint Ibase = ptIndex * uint(patchArea); //starting index Intensities
    uint Hbase = ptIndex * 21u; //starting index Hessians

}