#version 310 es

precision highp float;
precision highp int;
precision highp sampler2D;


// Each invocation = one thread = one main() call (here: one map point).
// Total invocations launched = numWorkGroupsX * local_size_x.
// How many run truly in parallel depends on the GPU scheduler / hardware (occupancy).
layout(local_size_x = 64,local_size_y = 1,local_size_z = 1) in;


//Uniforms (read-only constant for all invocations)
//uniform mat4        uPose;            //camera pose (change: needs to read/write, cannot be uniform)
uniform vec4        uK;                 //intrinsics (pre-scaled for each level)
uniform int         uPatchSize;         //size of patch
uniform int         uLevel;             //current level being processed
uniform int         uNPoints;           //the number of map points
uniform int         uIteration;         //current iteration
uniform uint        uEnableAlign;       //enable extra step to align small pixel error offsets
uniform uint        uSearchRadius;      //if enable align, how much to search for
uniform vec4        uSearchThreshold;   //search if MSE > threshold
uniform vec4        uRejectThreshold;   //reject if MSE > threshold
uniform vec4        uMaxShift;          //reject if shift > threshold
uniform float       uHuberK;            //used for huber weighting
uniform sampler2D   uNewTexture;        //current level image pyramid


//SSBO bindings (std430 -> standard for SSBOs for alignment of types:
//vec4 16 bytes, uint 4 bytes, float 4 bytes...
//Declare SSBO at slot 1,2,3... contains array ot type vec4/uint/float...
//buffer handle/block name, member of type, and the named variable to access in code
//access by bufferName.member[i]. ->PointsBuffer.pos[i];
//input
layout(std430, binding = 0) readonly buffer PointsBuffer       {vec4   pos[];  } inMapPoints;
layout(std430, binding = 1) readonly buffer RefValidBuffer     {uint   Valid[];} inValid;
layout(std430, binding = 2) readonly buffer IBuffer            {float  IRef[]; } inI;
layout(std430, binding = 3) readonly buffer JBuffer            {float  J[];    } inJ;

//output
layout(std430, binding = 4) writeonly buffer BBuffer            {vec4  B[];    } outB;

struct Chi2ValidData{float chi2;uint valid;};
layout(std430, binding = 5) writeonly buffer Chi2ValidBuffer    {Chi2ValidData data[];  } outChi2Valid;

//read and write
layout(std430, binding = 6) buffer AlignBuffer        {vec4  Align[]; } inOutAlign;
layout(std430, binding = 7) buffer PoseBuffer         {mat4  Tcw;} inOutPose;

//helper functions
//return bilinear interpolation (used for projection etc.)
float bilinearSample(float u, float v)
{
    ivec2 size = textureSize(uNewTexture,0); //sample texture at mip level 0
    //normalized coords. (divide by size), sample from pixel center therefore add 0.5 from corner
    vec2 uv = (vec2(u + 0.5, v + 0.5) / vec2(size));
    return texture (uNewTexture,uv).r; //does filtered sampling, texture has only red channel 32 bit float
}

float fastMSE(in uint idx, float u, float v, uint patchSize)
{
    uint patchArea = patchSize * patchSize;
    //sample 3 x 3 pixels only from patch, offset from center
    float patchCenter = float(patchSize - 1u) * 0.5;

    int step = int(patchCenter) - 1;
    if (step < 1) step = 1;
    int offs[3] = int[3](-step, 0, step);

    uint IBase = idx * uint(patchArea);

    float SSE = 0.0;
    int count = 0;

    //search patch
    for(int y = 0; y < 3; ++y)
    {
        for(int x = 0; x < 3; ++x)
        {
            int px = offs[x] + int(patchCenter);
            int py = offs[y] + int(patchCenter);
            uint pIdx = uint(py) * patchSize + uint(px);

            float IRef = inI.IRef[IBase + pIdx];

            float ux = u + float(offs[x]);
            float vx = v + float(offs[y]);
            float INew = bilinearSample(ux, vx);

            float residual = INew - IRef;
            SSE += residual * residual;
            ++count;
        }
    }

    if(count > 0)
    SSE /= float(count);

    return SSE;
}

float fullMSE(in uint idx, float u, float v, int patchSize)
{
    uint patchSizeU = uint(patchSize);
    uint patchArea = uint(patchSize) * uint(patchSize);
    float patchCenter = float(patchSize - 1) * 0.5;
    uint IBase = idx * uint(patchArea);

    float SSE = 0.0;
    int count = 0;

    for(int y = 0; y < patchSize; ++y)
    {
        for(int x = 0; x < patchSize; ++x)
        {
            uint pIdx = uint(y) * patchSizeU + uint(x);
            float IRef = inI.IRef[IBase + pIdx];

            float ux = u + float(x) - patchCenter;
            float vx = v + float(y) - patchCenter;
            float INew = bilinearSample(ux, vx);

            float residual = INew - IRef;
            SSE += residual * residual;
            ++count;
        }
    }

    if(count > 0)
    SSE /= float(patchArea);

    return SSE;
}

void fastSearchN(in uint idx, in int searchRadius, in uint patchSize,
float u, float v, out int outDu, out int outDv, out float bestScore, out float secondBestScore)
{
    //set to maximum values
    bestScore = 1.0/0.0;
    secondBestScore = 1.0/0.0;

    //output shifts
    outDu = 0;
    outDv = 0;

    //search radius u,v
    for(int dv = -searchRadius; dv <= searchRadius; ++dv)
    {
        for(int du = -searchRadius; du <= searchRadius; ++du)
        {
            //check score for this offset
            float score = fastMSE(idx, u+float(du), v+float(dv),patchSize);
            if(score < bestScore)
            {
                secondBestScore = bestScore;
                bestScore = score;
                outDu = du;
                outDv = dv;
            }
            else if(score < secondBestScore)
            {
                secondBestScore = score;
            }
        }
    }
}

void invalidatePoint(uint i)
{
    outB.B[i * 2u + 0u] = vec4(0.0);
    outB.B[i * 2u + 1u] = vec4(0.0);
    outChi2Valid.data[i].chi2 = 0.0;
    outChi2Valid.data[i].valid = 0u;
}

void main()
{
    //Variables assignment
    uint ptIndex = gl_GlobalInvocationID.x;

    ivec2 size = textureSize(uNewTexture,0); //sample texture at mip level 0
    uint patchSizeU = uint(uPatchSize);
    int  patchSizeI = uPatchSize;
    float patchCenter = float(patchSizeI - 1) * 0.5;
    uint patchArea = patchSizeU * patchSizeU;

    //safety margin for bilinear interpolation
    float border      = patchCenter + 2.0;

    //extra search in case align is on
    float searchRadius = float(uSearchRadius);
    float borderSearch = border + searchRadius;

    int level = uLevel;
    int iteration = uIteration;
    float huberK = uHuberK;




    //check invocation overflow
    if(ptIndex >= uint(uNPoints))
    {
        return;
    }
    //also check if RevValidBuffer?
    //(previous levels might set to invalid)
    if(inValid.Valid[ptIndex] == 0u)
    {
        invalidatePoint(ptIndex);
        return;
    }

    //project point to camera pose space
    vec4 ptPos = inMapPoints.pos[ptIndex];   //world pos
    vec4 ptPosCam = inOutPose.Tcw * ptPos;   //wrt to camera
    float X = ptPosCam.x;
    float Y = ptPosCam.y;
    float Z = ptPosCam.z;

    //check point behind camera
    if(Z <= 0.0)
    {
        invalidatePoint(ptIndex);
        return;
    }

    //project point to u,v image space
    float fx = uK.x;
    float fy = uK.y;
    float cx = uK.z;
    float cy = uK.w;

    //original point projection
    float u0 = fx * (X / Z) + cx;
    float v0 = fy * (Y / Z) + cy;

    int du = 0;
    int dv = 0;
    float mseFull = 0.0;
    bool valid = true;

    //used for thresholds, later needs to be properly expanded for image pyramids > 4
    int li = (level < 0) ? 0 : ((level > 3) ? 3 : level);
    float rejectThreshold = uRejectThreshold[li];
    float maxShift        = uMaxShift[li];
    float searchThreshold = uSearchThreshold[li];

    //Do alignment search only at iteration 0
    if(uEnableAlign == 1u)
    {
        if (iteration == 0)
        {
            //check border with extra pixels for search region
            if (u0 < borderSearch || v0 < borderSearch ||
            u0 >= float(size.x) - borderSearch || v0 >= float(size.y) - borderSearch)
            {
                valid = false;
            }
            else
            {
                //get fast MSE
                float mseFast = fastMSE(ptIndex, u0, v0, patchSizeU);

                //score is error (the lower the better)
                float bestScore = mseFast;
                float secondBestScore = 1.0/0.0;

                //if first try gives high error, search for better offset
                if (mseFast > searchThreshold)
                {
                    fastSearchN(ptIndex, int(uSearchRadius), patchSizeU,
                    u0, v0, du, dv, bestScore, secondBestScore);
                }

                //length of shift, avoid sqrt
                float shift = float(du*du + dv*dv);

                // ambiguity check
                bool ambiguous = false;
                if (!isnan(secondBestScore) && !isinf(secondBestScore) && secondBestScore > 1e-12)
                {
                    float ratio = bestScore / secondBestScore;
                    if (ratio > 0.95) ambiguous = true;
                }

                //full score at best offset
                mseFull = fullMSE(ptIndex, u0 + float(du), v0 + float(dv), patchSizeI);

                //reject or not
                if (ambiguous || shift > maxShift*maxShift || mseFull > rejectThreshold)
                    valid = false;
            }

            // write offsets to buffer for later iterations
            inOutAlign.Align[ptIndex] = vec4(float(du), float(dv), valid ? 1.0 : 0.0, mseFull);
        }
        else
        {
            //read offsets for (iterations > 0):
            vec4 alignmentBuffer = inOutAlign.Align[ptIndex];
            du = int(alignmentBuffer.x);
            dv = int(alignmentBuffer.y);
            valid = (alignmentBuffer.z > 0.5);
            mseFull = alignmentBuffer.w;
        }
    }
    else
    {
        //Could be removed entirely.
        //otherwise compute full MSE, without alignment search: du=dv=0,
        if (iteration == 0)
        {
            if (u0 < border || v0 < border || u0 >= float(size.x) - border || v0 >= float(size.y) - border)
                valid = false;
            else
            {
                mseFull = fullMSE(ptIndex, u0, v0, patchSizeI);
                if (mseFull > rejectThreshold) valid = false;
            }
            inOutAlign.Align[ptIndex] = vec4(0.0, 0.0, valid ? 1.0 : 0.0, mseFull);
        }
        else
        {
            vec4 alignmentBuffer = inOutAlign.Align[ptIndex];
            valid  = (alignmentBuffer.z > 0.5);
            mseFull = alignmentBuffer.w;
        }
    }

    // corrected center (du and dv are 0 if no alignment search is done)
    float uc = u0 + float(du);
    float vc = v0 + float(dv);

    //check borders
    if (!valid || uc < border || vc < border || uc >= float(size.x) - border || vc >= float(size.y) - border)
    {
        invalidatePoint(ptIndex);
        return;
    }



    //starting index of patch in buffer (stores all patches flat)
    uint IBase = ptIndex * uint(patchArea);

    vec4 b0 = vec4(0.0);
    vec4 b1 = vec4(0.0);
    float chi2 = 0.0;

    for(int y = 0; y < patchSizeI; ++y)
    {
        for(int x = 0; x < patchSizeI; ++x)
        {
            //stride index through patch
            uint pIdx = uint(y) * patchSizeU + uint(x);
            //reference image pixel intensity
            float IRef = inI.IRef[IBase + pIdx];

            //get current image pixel intensity
            float ux = uc + float(x) - patchCenter;
            float vx = vc + float(y) - patchCenter;
            float INew = bilinearSample(ux, vx);

            float residual = IRef - INew;
            float aResidual = abs(residual);
            float w = (aResidual <= huberK) ? 1.0 : (huberK / aResidual);

            uint JBase = (IBase + pIdx) * 6u;

            b0 += w * vec4(inJ.J[JBase+0u], inJ.J[JBase+1u], inJ.J[JBase+2u], inJ.J[JBase+3u]) * residual;
            b1 += w * vec4(inJ.J[JBase+4u], inJ.J[JBase+5u],0.0,0.0) * residual;

            chi2 += w * residual * residual;
        }
    }

    //write outputs
    if(valid)
    {
        outB.B[ptIndex*2u+0u] = b0;
        outB.B[ptIndex*2u+1u] = b1;
        outChi2Valid.data[ptIndex].chi2 = chi2;
        outChi2Valid.data[ptIndex].valid = 1u;
    }
    else
        invalidatePoint(ptIndex);

    return;

}